# Generated by Django 3.1.3 on 2020-12-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='email_address',
            field=models.EmailField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='count',
            field=models.IntegerField(),
        ),
    ]
